### ISSUE TITLE
Doesn't work on Catalina

### ISSUE THREAD

**Issue by ghost** [andrewn/brew-services-menubar#12] opened 2020-07-29 12:24 UTC
Menu shows up in the menu bar but no services are shown. This is 3.0.0 from Homebrew on Catalina 10.15.5

**Comment by stefansundin** [comment] 2020-09-07 05:02
Works fine for me. Do you have more information on your problem?

**Comment by Toontje** [comment] 2020-09-07 09:32
Not really. On initial install it works. Then, i don't know the condition, really, after a couple of reboots the application launches, but doesn't show any services. Not running, not stopped. It's like the menu doesn't open when the menu item in the menu bar is clicked.

**Comment by imxeno** [comment] 2020-09-23 12:14
> Works fine for me. Do you have more information on your problem?

I can also confirm that it works fine for me. I'm running macOS 10.15.6.

**Comment by Toontje** [comment] 2020-09-24 09:21
I noticed that on an external screen it always works correctly. It's on the main screen where the problem arises. I created two videos: main and external here: https://we.tl/t-N2sBjORMeS where you can see the behavior.

**Comment by Toontje** [comment] 2020-09-27 08:17
Ok, turns out that when external screens are connected the menu doesn't open up on the main laptop screen. On the external screen it does open. When the external screens are not connected, the menu opens up correctly on the main screen. This is reproduceable. If you have an external screen, of course.

**Comment by stefansundin** [comment] 2020-09-28 16:35
I was able to reproduce it as well.

**Comment by Toontje** [comment] 2020-09-29 09:54
> I was able to reproduce it as well.

Thank you!

**Comment by stefansundin** [comment] 2020-10-01 04:08
I have been searching a bit more on this, and I realized that it also happens to another app that I use, KeepingYouAwake.

Someone already filed an issue there, and they discovered that it only happens when you have the monitors set up in a vertical arrangement. https://github.com/newmarcel/KeepingYouAwake/issues/139#issuecomment-573832914

I switched my arrangement to have the monitors be side-by-side and the bug magically disappears for both apps.

There may be ways to work around this since some apps obviously do work, like Docker.

**Comment by KODerFunk** [comment] 2020-12-12 19:29
Works at Catalina 10.15.7

**Comment by Toontje** [comment] 2020-12-13 10:22
Yes, i found it with other applications as well. Seems to be an Apple issue then. Try to get that resolved any time soon. No chance.

**Comment by stefansundin** [comment] 2022-04-23 02:04
I can't repro this issue anymore on macOS Monterey 12.3.1.

**Comment by andrewn** [comment] 2022-11-10 10:45
Closing as seems to be fixed by the onward march of progress. 🙂

**Closed by andrewn** 2022-11-10 10:45 UTC
